apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deploy
  template:
    metadata:
      labels:
        app: mysql-deploy
    spec:
      volumes:
      - name: mysql-pv-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql-deploy
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name:  mysecret
              key: mysql-root-password
        - name: MYSQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name : mysecret
              key: mysql-user-password
        envFrom:
          -configMapRef: mysql-cm
        ports:
          - containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-pv-storage
