apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-deploy
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deploy
  template:
    metadata:
      labels:
        app: mysql-deploy
    spec:
      volumes:
      - name: mysql-pv-storage
        persistentVolumeClaim:
           claimName: mysql-pv-claim
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "R1234r"
          - name: MYSQL_USER
            value: "clarus"
          - name: MYSQL_PASSWORD
            value: "Clarusway_1"
          - name: MYSQL_DATABASE
            value: "phonebook"    
        ports: 
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-pv-storage
