apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: jamesclarusway/webserver
        name: webserver
        ports:
        - containerPort: 80
        env:
         - name: MYSQL_DATABASE_HOST
           value: "mysql-deploy.default.svc.cluster.local"
         - name: MYSQL_PASSWORD
           value: "Clarusway_1"
         - name: MYSQL_DATABASE
           value: "phonebook"
         - name: MYSQL_USER
           value: "clarus"
            